name: "CI"

on:
  pull_request:
    paths-ignore:
      - 'nvim/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'nvim/**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: nixos
            runs-on: ubuntu-latest
            build-target: nixosConfigurations.nixos.config.system.build.toplevel
          - platform: darwin
            runs-on: macos-latest
            build-target: darwinConfigurations.mac.system
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Flake check
        run: nix flake check --accept-flake-config

      - name: Build ${{ matrix.platform }} configuration
        run: nix build .#${{ matrix.build-target }} --accept-flake-config --show-trace
